definitions:
  user.createRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  user.createResponse:
    properties:
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/user:
    post:
      consumes:
      - application/json
      description: Add a new user
      parameters:
      - description: Create a new user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.createRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"username":"kong"}}'
          schema:
            $ref: '#/definitions/user.createResponse'
      summary: Add new user to the database
      tags:
      - user
swagger: "2.0"
